### ISSUE TITLE
compiler errors on the prototype

### ISSUE THREAD

**Issue by zkbitcoin** [jasonmorton/halo2deeplearning#7]
Hi, trying to learn this package , during assembly with rust toolchain nightly-2021-11-29-x86_64-apple-darwin) gives (below compiler output)

using halo2_proofs-0.2.0 in Cargo 

1. 

error[E0599]: the method `flatten` exists for array `[[T; HEIGHT]; WIDTH]`, but its trait bounds were not satisfied
  --> src/cnvrl_generic/util.rs:94:10
   |
94 |         .flatten()
   |          ^^^^^^^ method cannot be called on `[[T; HEIGHT]; WIDTH]` due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           `[[T; HEIGHT]; WIDTH]: Iterator`
           which is required by `&mut [[T; HEIGHT]; WIDTH]: Iterator`
           `[[T; HEIGHT]]: Iterator`
           which is required by `&mut [[T; HEIGHT]]: Iterator`

2.

error[E0599]: the method `flatten` exists for array `[[T; HEIGHT]; WIDTH]`, but its trait bounds were not satisfied
  --> src/cnvrl_generic/util.rs:96:27
   |
96 |         .zip(image_subset.flatten().iter())
   |                           ^^^^^^^ method cannot be called on `[[T; HEIGHT]; WIDTH]` due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           `[[T; HEIGHT]; WIDTH]: Iterator`
           which is required by `&mut [[T; HEIGHT]; WIDTH]: Iterator`
           `[[T; HEIGHT]]: Iterator`
           which is required by `&mut [[T; HEIGHT]]: Iterator`

3.

error[E0599]: the method `flatten` exists for array `[[halo2_proofs::plonk::Expression<F>; _]; _]`, but its trait bounds were not satisfied
   --> src/cnvrl_generic.rs:117:18
    |
117 |                 .flatten()
    |                  ^^^^^^^ method cannot be called on `[[halo2_proofs::plonk::Expression<F>; _]; _]` due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `[[halo2_proofs::plonk::Expression<F>; _]; _]: Iterator`
            which is required by `&mut [[halo2_proofs::plonk::Expression<F>; _]; _]: Iterator`
            `[[halo2_proofs::plonk::Expression<F>; _]]: Iterator`
            which is required by `&mut [[halo2_proofs::plonk::Expression<F>; _]]: Iterator`

4. 

error[E0061]: this function takes 1 argument but 2 arguments were supplied
    --> src/eltwise.rs:81:24
     |
81   |               let _ = cs.lookup("lk", |cs| {
     |  ________________________^^^^^^_----__-
     | |                        |
     | |                        expected 1 argument
82   | |                 let qlookup = cs.query_selector(qlookup);
83   | |                 vec![
84   | |                     (
...    |
92   | |                 ]
93   | |             });
     | |_____________- supplied 2 arguments
     |
note: associated function defined here
    --> //rust/src/halo2/halo2_proofs/src/plonk/circuit.rs:1009:12
     |
1009 |     pub fn lookup(
     |            ^^^^^^

**Comment by zkbitcoin** [comment]
project constructs are sensitive to rust toolchain , this success: nightly-2022-05-01-x86_64-apple-darwin

error related to cs.lookup thats just halo2 versioning (me using 0.20.) switching to the original resolves the signature

**Comment by zkbitcoin** [comment]
professor, also any possibility for a white paper on this, utilization of zk technology in this area is quite novel/fascinating, it would definitely facilitate deeper understanding of this prototype

**Comment by jasonmorton** [comment]
Thank you for the issue report, we will try to be more explicit about versions. The dependencies are fast-moving so we should probably pin to specific versions.  I'm not sure if there will be a whitepaper, but more documentation and examples are on the way.  Ok to close this issue?

**Comment by zkbitcoin** [comment]
> Thank you for the issue report, we will try to be more explicit about versions. The dependencies are fast-moving so we should probably pin to specific versions. I'm not sure if there will be a whitepaper, but more documentation and examples are on the way. Ok to close this issue?

yes,  thank you
